services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 10

  vk_from_youtube_service:
    build: ./app
    container_name: vk_from_youtube_service
    restart: always
    volumes:
      - ./data/db/videos.db:/app/videos.db
      - ./data/downloads:/app/downloads
      - ./data/images:/app/images
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  app-network: