services:
    youtube_to_vk:
        build:
            context: ../
            dockerfile: docker/Dockerfile
        restart: unless-stopped
        container_name: "youtube_to_vk"
        env_file:
            - ./../.env
        volumes:
            - ../src:/app/src
            - ../data/:/app/data/
            - ../docker/root.cron:/etc/crontabs/root
